name: buildAutomation_1-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm audit
      - run: npm run lint
      - run: npm run test
      - run: version=$(jq -r '.version' package.json)
      - run: echo version: $version
      - run: ./buildDockerImage.sh
      - run: echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
